---
version: '3.6'

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: guest
      POSTGRES_USER: pokemon_db_user
      POSTGRES_DB: pokemon_db
    ports:
        - 5432:5432


